spring.application.name=GraphQL

# Configura��o do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/my_postgres_DB
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update